[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "opdxread"
version = "0.1.2"
dependencies = [
    "numpy>=1.22",
]
description = "Lib for reading Vision64 profilometry data from .OPDx files."
readme = "README.md"
license = "LGPL-3.0-or-later"
authors = [{name = "Thomas Lockwood", email = "thomas.lockwood@uts.edu.au"}]

[project.urls]
Repository = "https://gtihub.com/djdt/opdxread"
